### ISSUE TITLE
Dev content review

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-testcontainers#1]
**Try what you’ll build**
- [x] remove "Run the following command to download or update ..." statment and the `docker pull...` command
- [ ] `mvn package` is not enough. Need `mvn package liberty:create liberty:install-feature liberty:deploy`

**Implementing integration tests**
- [x] `docker run --name postgres-container ...` -> `docker run --name postgres-container --rm ...`
- [x] `mvn liberty:devc -DdockerRunOpts="-e POSTGRES_HOSTNAME=172.17.0.2" ...`  -> `mvn liberty:devc -DdockerRunOpts="-e DB_HOSTNAME=172.17.0.2" ...`

**Starting Testcontainers**
- [x] "Define the `postgresContainer` test container to start up ..., and define the `inventoryContainer` test container ... " -> "Use `GenericContainer` class to create the `postgresContainer` test container to start up ..., and use the `LibertyContainer` custom class to create the `inventoryContainer` test container ... "
- [x] "The updated `setup` method ..." -> "The updated `setup()` method ..."
- [x] "In the case of Testcontainers, it starts Postgres and inventory containers." ->  "In the case of no running runtime, the test starts the `[hotspot]postgresContainer` and `[hotspot]inventoryContainer` test containers."
- [x] "After tests, the `tearDown` method..." -> "After tests, the `tearDown()` method..."

**Configuring Maven project**
- [x] "Also, add the `maven-failsafe-plugin` plugin,..." -> "Also, add and config the `maven-failsafe-plugin` plugin,..."

**Testing outside of development mode**
- [x] remove `docker rm postgres-container`

**Comment by shin19991207** [comment]
>  mvn package is not enough. Need mvn package liberty:create liberty:install-feature liberty:deploy

Used `maven-dependency-plugin` instead and added explanation at https://github.com/OpenLiberty/draft-guide-testcontainers/pull/3/commits/ffb4bb54330383741817db14d45e7cfa3cee70c8.

**Comment by gkwan-ibm** [comment]
**Starting Testcontainers**
- [x] "In the case of Testcontainers, it starts Postgres and inventory containers." -> "In the case of no running runtime, the test starts the `[hotspot]postgresContainer` and `[hotspot]inventoryContainer` test containers."
 - the hotspots better highlight the `postgresContainer.start()` and `inventoryContainer.start()` methods

**Configuring Maven project**
- [x] "Also, add and config ..." -> "Also, add and configure ..."
- [x] Move the "Because the `maven-dependency-plugin` ..." paragraph from **Try what you’ll build** to **Configuring Maven project** before the "Also, add and configure..." paragraph
