### ISSUE TITLE
Final end-to-end test

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-testcontainers#14]
- [x] Clear the `.m2` repository before running the tests
 - [x] Clone the repository with the `draft` branch
 - [x] Run `diff -r start/ finish/` and there is no differences except `tag` and `end` comments
 - [x] check that all dependencies/plugins in pom.xml are latest versions
 - [x] Read through the guide to check its appearance (contents, headings, paragraphs, code snippets, outputs, links, hotspots) of the guide on draft site
    - [x] ensure all hotspots work
    - [x] ensure all URLs work and open new tab
    - [x] follow the instructions in the guide to test end-to-end
        - Use the `copy` buttons instead of typing

**Comment by Ruilin-Ma** [comment]
Test the guide end-to-end on Linux; no issues were found.

**Comment by gkwan-ibm** [comment]
fixed PRs: #28, #29, #30
