### ISSUE TITLE
SME Review

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/guide-testcontainers#16]
## Documentation Issues

https://github.com/OpenLiberty/draft-guide-testcontainers/blob/8070ae3b434783f3e752fae9b687a43769a0eb49/README.adoc?plain=1#L41

Clarify which library does what:
```txt
Testcontainers is an open source library that utilizes the docker-java library which wraps Docker in a Java API.  Testcontainers then plugs into the lifecycle of test frameworks to provide containers as a resource at test time. 
```

---

https://github.com/OpenLiberty/draft-guide-testcontainers/blob/8070ae3b434783f3e752fae9b687a43769a0eb49/README.adoc?plain=1#L280

I would have a paragraph dedicated to the `Network` usage, something like: 

```txt
Because containers are isolated by default, make sure both containers use the same network for them to communicate.
By placing the containers within the same network the Liberty container can communicate with the Postgre using the hostname `localhost` and internal port `5432` instead of the externally mapped port.
```

This will make it so anyone reading the guide understands why using a Network is important, and how it relates to the server configuration. 

## Focus issues

The guide has you building docker images from Dockerfiles prior to running the Testcontainers test.
This is unnecessary as Testcontainers and build images on the fly from Dockerfiles. 

https://github.com/OpenLiberty/draft-guide-testcontainers/blob/8070ae3b434783f3e752fae9b687a43769a0eb49/finish/src/test/java/it/io/openliberty/guides/inventory/SystemResourceIT.java#L63

```java
private static ImageFromDockerFile postgreSQLImage = new ImageFromDockerFile().withDockerfile(Paths.get("../postgres/Dockerfile");
private static GenericContainer<?> postgresContainer = new GenericContainer<>(postgreSQLImage);
```

This way there is no reason to build the image prior to testing and no image is left in the testers environment after finishing the guide.

---

I do not agree with using dev mode in this guide.
I think it distracts from what the guide is supposed to focus on which is Testcontainers.

The integration test is already complicated enough for someone who is new to Testcontainers, but now there is a bunch of unnecessary logic to integrate both with the container AND dev mode.

---

In the LibertyContainer class you wait for a line in the logs: 
https://github.com/OpenLiberty/draft-guide-testcontainers/blob/8070ae3b434783f3e752fae9b687a43769a0eb49/finish/src/test/java/it/io/openliberty/guides/inventory/LibertyContainer.java#L30

But in the test class, you overwrite this configuration by waiting for a healthCheck: 
https://github.com/OpenLiberty/draft-guide-testcontainers/blob/8070ae3b434783f3e752fae9b687a43769a0eb49/finish/src/test/java/it/io/openliberty/guides/inventory/SystemResourceIT.java#L84

You should choose one and remove the other.
I would am partial to waiting for the line in the logs, because that will be most universal for developers.

## Technical Issues

Each container dumps their logs using the same logger.

https://github.com/OpenLiberty/draft-guide-testcontainers/blob/8070ae3b434783f3e752fae9b687a43769a0eb49/finish/src/test/java/it/io/openliberty/guides/inventory/SystemResourceIT.java#L87

It would be easier to tell which messages are coming from which container by giving each of them their own logger: 

```java
.withLogConsumer(new Slf4jLogConsumer(LoggerFactory.getLogger(LibertyContainer.class)));
```

---

I think we should also configure a database name instead of relaying on an automated name generated by the postgresql container so that if a user is using this guide as a starting point they know where they should configure the database name. 

https://github.com/OpenLiberty/draft-guide-testcontainers/blob/8070ae3b434783f3e752fae9b687a43769a0eb49/postgres/Dockerfile#L3-L6

```Dockerfile
# Create the admin user for PostgreSQL
ENV POSTGRES_USER admin
# Create the admin password for PostgreSQL
ENV POSTGRES_PASSWORD adminpwd
# Create the default database for PostgreSQL
ENV POSTGRES_DB admindb
```

```xml
    <variable name="db.hostname" defaultValue="localhost" />
    <variable name="db.portnum" defaultValue="5432" />
    <variable name="db.username" defaultValue="admin" />
    <variable name="db.password" defaultValue="adminpwd" />
    <variable name="db.database" defaultValue="admindb" />
```

## General Comments

Overall great guide!  I really like it just think it could some some refining.
Let me know if you need any additional help
FYI @gkwan-ibm

**Comment by gkwan-ibm** [comment]
hi @KyleAure Thanks for your review.

- Regarding using dev mode or not, we have different opinion. We will discuss your suggestion internally.
- Regarding the waitingFor, for general app in OL, yes, check the log is enough, but the inventory in this guide is better to check the db service.  We will see how to describe it clear.
