### ISSUE TITLE
Laura's review

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-testcontainers#25]
Within the limits of what I know about writing tests, I think this looks in pretty good shape as a guide.

Intro:
* The first couple of paras of the Intro (What you'll learn) are nice and clear but when it gets to "What is Testcontainers?", it jumps into the detail too quickly. eg "Testcontainers is an open-source library that utilizes the docker-java library, which wraps the Docker in a Java API." isn't an especially nice explanation of what Testcontainers is. Better would be something like "Testcontainers is an open-source library that provide containers as a resource at test time. This allows for consistent, portable testing environments especially when dealing with applications that have external resource dependencies such as databases, message queues, or web services." You could then go into the Docker part but I'm not even sure that's necessary here if you've already said that it provides containers - that's the important part. Then "By encapsulating these dependencies in containers, Testcontainers ensures a uniform testing setup and simplifies the configuration process." is good. Focus on what the library provides to the user and why it's a great idea; don't worry about explaining how it does it unless it's really important to know, but even then put that bit after the what/why part.

Otherwise, some style comments to fix throughout (I haven't quoted them all so check right through for similar instances):

* Can you get an ID review, pls? There are stylistic things that I think they'd catch/change. For example, never use "utilize" (there's no reason to use it instead of the simpler "use"); the use of "dev/test" repeatedly is a bit awkward/clumsy - I understand why but ID might have a better way to phrase it. Also, don't put the "dev/test" in parentheses twice in the paragraph; if it's the short version of a term, just use the short version after the first instance.
* Similarly "so that the .war file resides in the target directory, and the .jar PostgreSQL JDBC driver file resides in the" - just say "so that the .war file is in the target directory, and the .jar PostgreSQL JDBC driver file is in the" - no need to say "resides". Keep it simple and unpretentious.
* Don't keep using the future tense except in the What you'll learn section. For example, in the "Building a test container for Open Liberty" section, it starts "Next, you’ll learn to create a custom class that extends..." but the purpose of these sections is to just get on with it; not to tell them what they'll learn. Instead say "Next, create a custom class that extends...". The only time you talk in terms of what the user will learn is in the "What you'll learn" section. After that, don't talk around it; just instruct them in what to do and why they're doing it. Same applies for all sections except the "What you'll learn" section.
* As another example, in the "Configuring the Maven project" section, start with "Next, prepare your Maven project for test execution by adding the necessary dependencies for Testcontainers and logging, setting up Maven to copy the PostgreSQL JDBC driver during the build phase, and configuring the Liberty Maven Plugin to handle PostgreSQL dependency."
* General style comment: don't use the future tense at all (except in What you'll learn section). So say "You see the following output:" not "You will see the following output:". Again, an ID review should catch this kind of thing.

Thanks

**Comment by yeekangc** [comment]
Hi @shin19991207.  I think this has been resolved, correct?  Please close if so.

**Comment by gkwan-ibm** [comment]
close
- resolved
