### ISSUE TITLE
Dev content review

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-testcontainers#8]
**Building Testcontainer for Open Liberty**
- [x] add a statement for users to learn more TestContainers APIs and provide doc/javadoc link
    - between "The Wait.forLogMessage() method ..." and "Now you can set up trace logging for your tests."
    - need to search the doc/javadoc

**Implementing integration tests to use Testcontainers**
- [x] the dev mode output should change `IP address [ 172.17.0.2 ]...` to `IP address [ 172.17.0.3 ]...`
  - because `172.17.0.2` is used by the postgres db

<del>**Configuring Maven project**<del>
<del>- [ ] Didn't see `Testing by dev mode or local runtime` message<del>
<del>  - need to investigate. Probably causing by `devc` and log4j. I cannot fix. Remove the statement.<del>

**Running tests in a CI/CD pipeline**
- [x] add `export TESTCONTAINERS_RYUK_DISABLED=true` before `mvn verify` as same as in the **Try what you’ll build** section

**General**    
- [x] LibertyContainer.java at [line 24](https://github.com/OpenLiberty/draft-guide-testcontainers/blob/348a2ad940fc1700d629a2351f67776ba1855022/finish/src/test/java/it/io/openliberty/guides/inventory/LibertyContainer.java#L24C10-L24C10), should not contain a tab char before `super`

**Comment by shin19991207** [comment]
> Configuring Maven project
> - [ ] Didn't see Testing by dev mode or local runtime message
> - need to investigate. Probably causing by devc and log4j. I cannot fix. Remove the statement.

Confirmed that the output shows up properly.
